# -*- coding: utf-8 -*-
CAMERA = "Yes"
BATTERY_LIFE = "Yes"
PROCESSOR = "Yes"
MEMORY = "Yes"
SCREEN_RESOLUTION = "Yes"

CAMERA_NO = "No"
BATTERY_LIFE_NO = "No"
PROCESSOR_NO = "No"
MEMORY_NO = "No"
SCREEN_RESOLUTION_NO = "No"

CAMERA_CODE_YES = [1]
BATTERY_LIFE_CODE_YES = [1]
PROCESSOR_CODE_YES = [1]
MEMORY_CODE_YES = [1]
SCREEN_RESOLUTION_CODE_YES = [1]

CAMERA_CODE_NO = [0]
BATTERY_LIFE_CODE_NO = [0]
PROCESSOR_CODE_NO = [0]
MEMORY_CODE_NO = [0]
SCREEN_RESOLUTION_CODE_NO = [0]

